### ISSUE TITLE
Missing `main.py` file?

### ISSUE THREAD

**Issue by baronet2** [reidmcy/set-based-prompting#1]
Hi there, I came across your paper on arXiv and would love to experiment with your methods!

The `README` mentions a `main.py` file, but that file doesn't seem to be in the repository. Is there a different way I should run the tests?

**Comment by reidmcy** [comment]
Thanks for letting me know. I've pushed `main.py`.

I'm in the process of updating the code for a more formal release since the paper was accepted, so things will likely change soon. If I miss anything else let me know.

**Comment by baronet2** [comment]
Thanks @reidmcy !

I'm now getting `ModuleNotFoundError: No module named 'order_independent_llm'` - is this a package I can install from somewhere?

**Comment by baronet2** [comment]
Thanks, @reidmcy ! I had to fix the package name (see #2 ) but after that it worked!
